
package server.ws02.cxf.spring;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderWSImplService", targetNamespace = "http://spring.cxf.ws02.server/", wsdlLocation = "http://localhost:8081/orderWS?wsdl")
public class OrderWSImplService
    extends Service
{

    private final static URL ORDERWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDERWSIMPLSERVICE_EXCEPTION;
    private final static QName ORDERWSIMPLSERVICE_QNAME = new QName("http://spring.cxf.ws02.server/", "OrderWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/orderWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERWSIMPLSERVICE_WSDL_LOCATION = url;
        ORDERWSIMPLSERVICE_EXCEPTION = e;
    }

    public OrderWSImplService() {
        super(__getWsdlLocation(), ORDERWSIMPLSERVICE_QNAME);
    }

    public OrderWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERWSIMPLSERVICE_QNAME, features);
    }

    public OrderWSImplService(URL wsdlLocation) {
        super(wsdlLocation, ORDERWSIMPLSERVICE_QNAME);
    }

    public OrderWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERWSIMPLSERVICE_QNAME, features);
    }

    public OrderWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderWS
     */
    @WebEndpoint(name = "OrderWSImplPort")
    public OrderWS getOrderWSImplPort() {
        return super.getPort(new QName("http://spring.cxf.ws02.server/", "OrderWSImplPort"), OrderWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderWS
     */
    @WebEndpoint(name = "OrderWSImplPort")
    public OrderWS getOrderWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://spring.cxf.ws02.server/", "OrderWSImplPort"), OrderWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERWSIMPLSERVICE_EXCEPTION!= null) {
            throw ORDERWSIMPLSERVICE_EXCEPTION;
        }
        return ORDERWSIMPLSERVICE_WSDL_LOCATION;
    }

}
