
package server.ws02.cxf.spring;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderWS", targetNamespace = "http://spring.cxf.ws02.server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns server.ws02.cxf.spring.Order
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrderById", targetNamespace = "http://spring.cxf.ws02.server/", className = "server.ws02.cxf.spring.GetOrderById")
    @ResponseWrapper(localName = "getOrderByIdResponse", targetNamespace = "http://spring.cxf.ws02.server/", className = "server.ws02.cxf.spring.GetOrderByIdResponse")
    public Order getOrderById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
