
package server.datetype;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DateTypeWSImplService", targetNamespace = "http://datetype.server/", wsdlLocation = "http://127.0.0.1:8989/dateType/dateTypews?wsdl")
public class DateTypeWSImplService
    extends Service
{

    private final static URL DATETYPEWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DATETYPEWSIMPLSERVICE_EXCEPTION;
    private final static QName DATETYPEWSIMPLSERVICE_QNAME = new QName("http://datetype.server/", "DateTypeWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8989/dateType/dateTypews?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATETYPEWSIMPLSERVICE_WSDL_LOCATION = url;
        DATETYPEWSIMPLSERVICE_EXCEPTION = e;
    }

    public DateTypeWSImplService() {
        super(__getWsdlLocation(), DATETYPEWSIMPLSERVICE_QNAME);
    }

    public DateTypeWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATETYPEWSIMPLSERVICE_QNAME, features);
    }

    public DateTypeWSImplService(URL wsdlLocation) {
        super(wsdlLocation, DATETYPEWSIMPLSERVICE_QNAME);
    }

    public DateTypeWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATETYPEWSIMPLSERVICE_QNAME, features);
    }

    public DateTypeWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DateTypeWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DateTypeWS
     */
    @WebEndpoint(name = "DateTypeWSImplPort")
    public DateTypeWS getDateTypeWSImplPort() {
        return super.getPort(new QName("http://datetype.server/", "DateTypeWSImplPort"), DateTypeWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DateTypeWS
     */
    @WebEndpoint(name = "DateTypeWSImplPort")
    public DateTypeWS getDateTypeWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://datetype.server/", "DateTypeWSImplPort"), DateTypeWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATETYPEWSIMPLSERVICE_EXCEPTION!= null) {
            throw DATETYPEWSIMPLSERVICE_EXCEPTION;
        }
        return DATETYPEWSIMPLSERVICE_WSDL_LOCATION;
    }

}
