
package server.datetype;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DateTypeWS", targetNamespace = "http://datetype.server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DateTypeWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<server.datetype.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentByPrice", targetNamespace = "http://datetype.server/", className = "server.datetype.GetStudentByPrice")
    @ResponseWrapper(localName = "getStudentByPriceResponse", targetNamespace = "http://datetype.server/", className = "server.datetype.GetStudentByPriceResponse")
    public List<Student> getStudentByPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0);

    /**
     * 
     * @return
     *     returns server.datetype.GetAllStudentsMapResponse.Return
     */
    @WebMethod
    @WebResult(name = "_return", targetNamespace = "")
    @RequestWrapper(localName = "getAllStudentsMap", targetNamespace = "http://datetype.server/", className = "server.datetype.GetAllStudentsMap")
    @ResponseWrapper(localName = "getAllStudentsMapResponse", targetNamespace = "http://datetype.server/", className = "server.datetype.GetAllStudentsMapResponse")
    public server.datetype.GetAllStudentsMapResponse.Return getAllStudentsMap();

    /**
     * 
     * @param arg0
     * @return
     *     returns server.datetype.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentById", targetNamespace = "http://datetype.server/", className = "server.datetype.GetStudentById")
    @ResponseWrapper(localName = "getStudentByIdResponse", targetNamespace = "http://datetype.server/", className = "server.datetype.GetStudentByIdResponse")
    public Student getStudentById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://datetype.server/", className = "server.datetype.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://datetype.server/", className = "server.datetype.AddStudentResponse")
    public boolean addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        Student arg0);

}
